### ISSUE TITLE
rsplit is receiving "required" only

### ISSUE THREAD

**Issue by vishvendrasingh** [artisangang/node-input-validator#14]
rsplit[rs].split is not a function

TypeError: rsplit[rs].split is not a function
    at Validator.parseRules (/var/www/api/node_modules/node-input-validator/src/index.js:385:39)

**Comment by artisangang** [comment]
Please share steps to reproduce. Better if you can share code snippet.

**Comment by artisangang** [comment]
This crash is in case of using non-string rules. For example:

```javascript
let v = new Validator(req.body, {name: ['required'], email: function () {}});
```

Or you might be using Array of rule in Validator constructor. To use array of rules: https://www.npmjs.com/package/node-input-validator#array-of-rules

If there is any other scenario of this crash, please share your code snippet.

**Comment by vishvendrasingh** [comment]
Hi @artisangang here is the code 

`
const v = require('node-input-validator');
let validator =  new v( req.body, {
        country_code:'required',
        mobile: 'required|digitsBetween:6,16',
        _a: 'required',
        _o:'required'
    });

 validator.check().then(function (matched) {
        if (!matched) {
            return res.status(422).send(validator.errors);
        }
    });
`

**Comment by artisangang** [comment]
You code works fine for me, Please check it at: https://repl.it/@singhar/node-input-validator. 
See if you can reproduce the issue.

**Comment by vishvendrasingh** [comment]
Yes I checked! this issue can be seen in `express` only version - 4.16.1.

**Comment by artisangang** [comment]
Can you share your express sample code with me to reproduce this issue.
