### ISSUE TITLE
'Zero'  validation return  false when decimal validation

### ISSUE THREAD

**Issue by sibiklpm** [artisangang/node-input-validator#15]
0 : 'required|decimal'  - working fine up to 3.1.0 version. (return true)
But in latest versions its return false

**Comment by artisangang** [comment]
Please  share full code snippet.

**Comment by artisangang** [comment]
May this commit fix it: [ac54ac2583c24ee7f28b050371266e22d0633220](https://github.com/artisangang/node-input-validator/commit/ac54ac2583c24ee7f28b050371266e22d0633220?short_path=4ac32a7#diff-4ac32a78649ca5bdd8e0ba38b7006a1e)

It was due to is empty check, 0 considered as false.

**Comment by artisangang** [comment]
Fixed in version 3.5
