### ISSUE TITLE
Breaking change beetween 3.1.0 and 3.5.0

### ISSUE THREAD

**Issue by cacharrin** [artisangang/node-input-validator#16]
Hi, there is a breaking change beetween 3.1.0 and 3.5.0 versions

I had an endpoint where i send a json like:

``` 
{
    is_group: false,
    //other data
}
```

In the backend, I have schema defined as:

```
const schema = {
      is_group: "boolean:true,false",
      //other data
};
```

That worked perfectly on 3.1.0... after upgrade to 3.5.0 it always throw error, no matter which value is sent.

What I need is to allow a boolean field to be true or false, but not allow 1, 0, 'true', 'false', '1' or '0'...

What can i do?

**Comment by cacharrin** [comment]
I found also that in 3.1.0 version, the boolean validator receive the `value` as `string`... while in 3.5.0 it receives the `value` as a `boolean`

**Comment by artisangang** [comment]
I tried my best to maintain schematic version, but some get skipped. In earlier versions all values were got converted to string before passed down to rules. That behavior has been changed due to some rules required to preserve values types example arrays and objects etc.

**Comment by artisangang** [comment]
Boolean rule will pass with boolean, string, integer bits(0,1) in case of using default seed ie. ([true, false, 'true', 'false', 0, 1, '0', '1']) provided within rule. But when you use custom seed for boolean rule it will be treated as string. Example of your case:

```javascript
const v = new Validator(
            { attribute: false },
            { attribute: 'boolean:true,false' }
        );
```
In this case boolean value is compared against string seed. You need to pass value as string or use inbuilt seed.

**Comment by cacharrin** [comment]
I just implemented my own validator...


```
Validator.extend("bool", async (field, value, _args) => {
  if (value !== true && value !== false) {
    return false;
  }
  return true;
});
```

Thanks for your feedback ;)
