### ISSUE TITLE
How to handle server side validation with mysql 

### ISSUE THREAD

**Issue by shobhitsharma2018** [artisangang/node-input-validator#5]
app.post('/addProduct', function (req, res) {
    var validateRes = new validator({name: req.body.name, email: req.body.email}, {name: 'required|minLength:5', email: 'required|email|minLength:5'});
    validateRes.addPostRule(async function (input) {
        var _this = this;
        //this.validator.addError('email', 'custom', 'email cannot contain username'); 
        await connection.query('SELECT * from product where name ="' + input.name + '"', function (error, results) {
            if (!error) { 
                 validator.addError('name', 'custom', 'The product name already exist.');
            }
        });
    });
    validateRes.check().then(function (matched) {
        if (matched === true) {
            res.send(JSON.stringify({"status": 200, "error": null, "response": matched}));
        } else {
            res.send(JSON.stringify({"status": 200, "error": validateRes.errors, "response": null}));
        }
    });
});
await and async not working here please help me how can we validation server side

**Comment by artisangang** [comment]
async/await works with promises. You are using await with non-promise.  
For database validation, you need to extend module. Please read documentation.

```js
const validator = require('node-input-validator');


validator.extend('uniqueProduct', async function (field, value) {

    let valid = await new Promise((resolve, reject) => {
        connection.query('SELECT * from product where name = ? limit 1', [value], function (error, results) {
            if (results.length) {
                this.validator.addError(field, 'uniqueProduct');

                return resolve(true);
            }

            resolve(false);
        });
    });

    return valid;
})

validator.messages({
    uniqueProduct: 'The product name already exist.'
});


```

```js
app.post('/addProduct', function (req, res) {

    var validateRes = new validator({
        name: req.body.name,
        email: req.body.email
    },
        {
            name: 'required|minLength:5|uniqueProduct',
            email: 'required|email|minLength:5'
        });


    validateRes.check().then(function (matched) {
        if (matched === true) {
            res.send(JSON.stringify({ "status": 200, "error": null, "response": matched }));
        } else {
            res.send(JSON.stringify({ "status": 200, "error": validateRes.errors, "response": null }));
        }
    });
});
```
