### ISSUE TITLE
How to dynamic get attributes value

### ISSUE THREAD

**Issue by shobhitsharma2018** [artisangang/node-input-validator#6]
validator.messages({
    required: 'The :attribute field must not be empty.',
    minLength: 'The :attribute field must be min 6 lenght'
});

Is there any dynamic variable like :attribute for which can get attribute value dynamic for example 
"  minLength: 'The :attribute field must be min :{Attr_Value} lenght'"

**Comment by artisangang** [comment]
:attribute will be replaced with field name and placeholder for options passed to rules should be :arg0,:arg1 ...n

For example:
between:5,10 -> between::arg0,:arg1

{username: "required|minLength:50"}
minLength: 'The :attribute must be min :arg0 length'
output: The username must be of 50 length.

{age: "required|between:18,35"}
minLength: 'The :attribute must be between :arg0 and :arg1'
output: The age must be between 18 and 35.

**Comment by artisangang** [comment]
:value placeholder to show value in message.
