### ISSUE TITLE
Adjust validation message for minLength rule

### ISSUE THREAD

**Issue by elijah-ezaga** [artisangang/node-input-validator#8]
Currently, the default validation message for the minLength rule says: 
The field value is malformed.

**Comment by artisangang** [comment]
Thanks for reporting. This will be resolved with next release soon.
Temporary fix: 
```js
Validator.messages({minLength: 'Your custom message.'});
```

**Comment by elijah-ezaga** [comment]
Exactly. I had to use that.

**Comment by artisangang** [comment]
Fixed
