### ISSUE TITLE
The nullable validation rule throws an error

### ISSUE THREAD

**Issue by leouze** [artisangang/node-input-validator#9]
When used, it throws an error saying:

`UnhandledPromiseRejectionWarning: Error: Invalid Validation Rule: nullable does not exist
    at Rules.validate`

**Comment by artisangang** [comment]
Please post code snippet to reproduce the issue.  
Version of nodejs and node-input-validator?

**Comment by leouze** [comment]
@artisangang Sorry, I am using the lower version on my project. I just updated and it worked.
